package com.yfy.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yfy.db.User;
import com.yfy.greendao.KeyValueDb;

import com.yfy.greendao.UserDao;
import com.yfy.greendao.KeyValueDbDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig keyValueDbDaoConfig;

    private final UserDao userDao;
    private final KeyValueDbDao keyValueDbDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        keyValueDbDaoConfig = daoConfigMap.get(KeyValueDbDao.class).clone();
        keyValueDbDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        keyValueDbDao = new KeyValueDbDao(keyValueDbDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(KeyValueDb.class, keyValueDbDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        keyValueDbDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public KeyValueDbDao getKeyValueDbDao() {
        return keyValueDbDao;
    }

}
